### ISSUE TITLE
apt-get update fails

### ISSUE THREAD

**Issue by Duckle29** [geerlingguy/docker-debian8-ansible#7]
apt-get update fails, as there seems to be an issue with the source file.

This seems to solve the issue: https://superuser.com/questions/1423486/issue-with-fetching-http-deb-debian-org-debian-dists-jessie-updates-inrelease

```bash
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by atj** [comment]
I'm seeing this too. It looks like it's been fixed in the base image but this hasn't triggered a rebuild of this image:

https://github.com/docker-library/official-images/pull/5609

**Comment by geerlingguy** [comment]
That is weird, not sure why my image build hasn't been triggered. I'll try manually triggering one, then please let me know if it works.

**Comment by geerlingguy** [comment]
New version exists: https://cloud.docker.com/repository/registry-1.docker.io/geerlingguy/docker-debian8-ansible/builds/b090a409-7868-4e24-9af1-8b916905b56b

Please let me know if this works for you now!

**Comment by Duckle29** [comment]
```bash
fatal: [instance]: FAILED! => {"changed": false
 "cmd": "apt-get update"
 "msg": "W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored
 or old ones used instead."
 "rc": 100
 "stderr": "W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored
 or old ones used instead.
"
"stderr_lines": [
"W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)"
""
"E: Some index files failed to download. They have been ignored or old ones used instead."]

"stdout": "Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie-updates InRelease [7340 B]
Get:3 http://deb.debian.org jessie Release.gpg [2420 B]
Get:4 http://deb.debian.org jessie Release [148 kB]
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [824 kB]
Get:6 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.1 MB in 6s (1637 kB/s)
"
"stdout_lines": [
"Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]"
"Ign http://deb.debian.org jessie InRelease"
"Get:2 http://deb.debian.org jessie-updates InRelease [7340 B]"
"Get:3 http://deb.debian.org jessie Release.gpg [2420 B]"
"Get:4 http://deb.debian.org jessie Release [148 kB]"
"Get:5 http://security.debian.org jessie/updates/main amd64 Packages [824 kB]"
"Get:6 http://deb.debian.org jessie/main amd64 Packages [9098 kB]"
"Fetched 10.1 MB in 6s (1637 kB/s)"]}
```

Odd, I still get this issue running "molecule test" on https://github.com/sopel-irc/ansible-sopel
